/* ------------------------------------------
   Backend & Bridge common
--------------------------------------------- */
const cat = require('./createAsyncType')

module.exports = {
  events: {
    CP_ADAPTOR_GET_BY_AUTH_TOKEN: cat('CP_ADAPTOR_GET_BY_AUTH_TOKEN'),
    CP_ADAPTOR_UPDATE_ONLINE_STATE: cat('CP_ADAPTOR_UPDATE_ONLINE_STATE'),
    CP_BACKEND_GET_SETTINGS: cat('CP_BACKEND_GET_SETTINGS'),

    BE_ADAPTOR_UPDATE_LISTENING_STATE: 'BE_ADAPTOR_UPDATE_LISTENING_STATE',
    BE_ADAPTOR_UPDATE_ONLINE_STATE: 'BE_ADAPTOR_UPDATE_ONLINE_STATE',
    BE_ADAPTOR_BULK_UPDATE_LISTENING_STATE: 'BE_ADAPTOR_BULK_UPDATE_LISTENING_STATE',
    BE_ADAPTOR_UPDATE_EXCLUSIVE_STATE: 'BE_ADAPTOR_UPDATE_EXCLUSIVE_STATE',
    BE_ADAPTOR_UPDATE: 'BE_ADAPTOR_UPDATE',
    BE_ADAPTOR_DELETE: 'BE_ADAPTOR_DELETE'
  }
}
